[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn prisma generate", "NODE_OPTIONS='--max-old-space-size=4096' yarn build"]

[start]
cmd = "yarn start"
