[phases.setup]
nixPkgs = ['nodejs-20_x', 'yarn']

[phases.install]
cmds = [
  'cd /app',
  'yarn install --frozen-lockfile'
]

[phases.build]
cmds = [
  'cd /app',
  'yarn prisma generate',
  'yarn build'
]

[start]
cmd = 'cd /app && yarn start'

[variables]
NODE_ENV = 'production'
